<?php
date_default_timezone_set('Asia/Tokyo');
require 'vendor/autoload.php';
require './config.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-07 at 18:11:53.
 */
class TeapotQueryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    function testExecute()
    {
        ini_set('xdebug.var_display_max_children', -1);
        ini_set('xdebug.var_display_max_data', -1);
        ini_set('xdebug.var_display_max_depth', -1);
        $q = new \MyLib\TeapotQuery(new \MyLib\TeapotCtrl('http://teapot-api.bodic.org/api/v1/sparql', 'http://teapot-api.bodic.org/api/v1/places'));
        $ret = $q->columns(['?s', '?p', '?o'])
          ->distinct()
          ->where('?s', '?p', '?o')
          ->filter('!isBlank(?s)')
          ->limit(1)
          ->orderby('?s')
          ->execute();
        $this->assertEquals(
            '{"resultCode":0,"errorMsg":null,"contents":{"head":{"vars":["s","p","o"]},"results":{"bindings":[{"s":{"type":"uri","value":"http:\/\/teapot.bodic.org\/dataset\/aedLocation"},"p":{"type":"uri","value":"http:\/\/www.w3.org\/1999\/02\/22-rdf-syntax-ns#type"},"o":{"type":"uri","value":"http:\/\/teapot.bodic.org\/type\/dataset"}}]}}}',
            json_encode($ret),
            '正常の場合'
        );
    }
}
